### ISSUE TITLE
Holy Contributors

### ISSUE THREAD

**Issue by TeriaKatayoki** [TeriaKatayoki/HolyC#1]
Xin chào Coder, Tôi là TeriaK. Bạn muốn trở thành developer cho **project HOLY** - Hạ Hòa olympiad, mong bạn có thể để lại comment ở đây. Xin cảm ơn.
@TeriaKatayoki

**Comment by wasabixxx** [comment]
Hello anh

**Comment by sogiria** [comment]
hello a

**Comment by wasabixxx** [comment]
Wibu chúa

**Comment by TeriaKatayoki** [comment]
Hiện tại anh đang có ca học chiều, để tối anh add contributor nhé
